apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    #add an ingress controller based on the nginx project
    kubernetes.io/ingress.class: nginx
    #rewrites route api uris--> remove /api and keep it as /
    # i.e.: we dont need to specifically write for /api
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        #match uris and route accordingly
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000